### PR TITLE
Refactor and make qos, retained and cleanSession configurable

### PR DESCRIPTION
**Pull request by sbaeurle**
Even though i tried the procedure described in #3, I was unable to connect to the gerrit instance of your project.

Thus I simply create a PR here.

The error is the following:
image

### CODE REVIEW

**Comment by tlessig** [comment]
Configuration of qos, retained and cleanSession seems to be a pretty good idea. Thanks a lot!

**Comment by sbaeurle** [comment]
The usage of a logger instead of console.log may also fix #5

**Comment by mhuin** [comment]
Hello,
Thanks for your contribution! We don't handle Github PRs so worst case scenario I'll move this PR to our gerrit manually.

However it is odd that you couldn't log into the service. @sbaeurle could you join our matrix channel: https://matrix.to/#/#softwarefactory-project:matrix.org at your convenience so we can investigate the issue? You can ping me there.

**Comment by sbaeurle** [comment]
see https://softwarefactory-project.io/r/c/software-factory/keycloak-event-listener-mqtt/+/27774

**Pull request closed without merging**
